version: 2.1
jobs:
  build:
    working_directory: ~/repo/portfolio-react-app
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Print Current Directory 1
          command: pwd
      - run:
          name: Install Dependencies
          command:  |
            cd portfolio-react-app && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Print Current Directory 2
          command: pwd
      # - run:
      #     name: Install Netlify CLI
      #     command: npm install netlify-cli
      - run:
          name: Build React App
          command: |
            cd portfolio-react-app && npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
      - run:
          name: Print Current Directory 3
          command: |
            pwd
            echo "Listing Files:"
            ls -la
      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build

       
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main